dist: xenial
language: python
python: 2.7
virtualenv:
  system_site_packages: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:fontforge/fontforge'
    packages:
      - fontforge
      - python-fontforge

install:
  - pip install -r requirements.txt

script:
  - make
  - make check
